version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: jewmichmainsql
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     volumes:
       - "./html/:/var/www/html"
       - "./secrets:/var/www/secrets"
     build:
        context: .
        dockerfile: Dockerfile-wordpress
     links:
       - db
     ports:
       - "8000:80"
     restart: always
     env_file: ./secrets/secrets.env
