version: '2'

services:
   db:
     image: mysql:8.0.31
     ports:
       - "3306:3306"
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: jewmichmainsql
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   mailcatcher:
      image: schickling/mailcatcher
      restart: always
      ports:
         - "1080:1080"

   wordpress:
     build:
        context: .
        dockerfile: Dockerfile-wordpress
        args:
           - UID
     depends_on:
       - db
       - mailcatcher
     volumes:
       - "..:/var/www/"
       # Override VOLUME in Wordpress base image
       - "../html/:/var/www/html"
     links:
       - db
     ports:
       - "80:80"
     restart: always
