version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
     ports:
       - "3306:3306"
     restart: always
     user: "${UID}"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: jewmichmainsql
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   mailcatcher:
      image: schickling/mailcatcher
      restart: always
      ports:
         - "1080:1080"

   wordpress:
     build:
        context: .
        dockerfile: Dockerfile-wordpress
        args:
           - UID
     depends_on:
       - db
       - mailcatcher
     volumes:
       - "..:/var/www/"
       # Override VOLUME in Wordpress base image
       - "../html/:/var/www/html"
     links:
       - db
     ports:
       - "80:80"
     restart: always
