FROM wordpress:4-php7.0-apache

ARG UID
# assign host UID to www-data
RUN usermod -u $UID www-data

# Need the calendar functions for Jewmich sidebar and event-related code
# Unzip, git, and subversion are needed by  composer
RUN apt-get update && \
	apt-get install -qq -y unzip git subversion vim-tiny && \
	docker-php-ext-install calendar && \
	pecl install xdebug && \
	docker-php-ext-enable xdebug && \
	echo -e "xdebug.profiler_enable_trigger=on\nxdebug.profiler_output_dir=/var/www/html" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


COPY docker-entrypoint.sh /usr/local/bin
